Frontend Student Page Complete
digital-futures-academy/atlas-frontend pull request #15
Opened 2021-08-24 15:21 UTC by themegatree

AT-16: Students page, listing all students

2021-08-24 15:27 UTC, dearshrewdwit requested changes
Nice

2021-08-24 15:27 UTC, dearshrewdwit commented on src/components/Students/Student.js
> +  console.log(props.index)
remove debugging statement

2021-08-24 15:27 UTC, dearshrewdwit commented on src/components/Students/Student.js
> +
remove whitespace

2021-08-24 15:27 UTC, dearshrewdwit commented on src/components/Students/Students.js
> +      .then(data => this.setState({students: data.students.sort((a,b)=> (a.lastName > b.lastName) ? 1: -1)}));
Let's extract this to a function to help with clarity (is it DESC?)

```js
sortByLastNameDesc(students) {
  return students.sort((a,b) => (a.lastName > b.lastName) ? 1 : -1
}

// in other func
this.setState({students: this.sortByLastName(data.students)}
```

2021-08-24 15:48 UTC, dearshrewdwit submitted a review, later dismissed

2021-08-24 16:04 UTC, dearshrewdwit approved these changes

2021-08-25 08:38 UTC, RyanVanDijck approved these changes
Looks fine to me.

2021-08-25 08:38 UTC, merged