AT
digital-futures-academy/atlas-frontend pull request #16
Opened 2021-08-24 16:25 UTC by FractalFraction

Co-authored-by b7rch4 james.birchall4@btinternet.com

https://dfacademy.atlassian.net/jira/software/projects/AT/boards/4?selectedIssue=AT-36

Problem: The dashboard page only contained text elements, wanted to add some visual fidelity to the page using charts. 

Solution: Added doughnut and bar charts from chartjs to visualise the gender, background and challenge ratio data.

2021-08-24 16:29 UTC, dearshrewdwit requested changes

2021-08-24 16:29 UTC, dearshrewdwit commented on src/components/Dashboard/buildData.js
> +const buildLabelArray = (data) => {
Simplify

```js
const buildLabelArray = (data) => data.map(obj => obj.type );
const buildNumberArray = (data, attr) => data.map(obj => parseInt(obj[attr]));
```

2021-08-24 16:29 UTC, dearshrewdwit commented on src/components/Dashboard/buildData.js
> +  const dataObj = {
Simplify: 
```js
return dataObj = {
```

2021-08-24 16:29 UTC, dearshrewdwit commented on src/components/Dashboard/buildData.js
> +  const dataObj = {
And then remove the `return` below

2021-08-24 16:40 UTC, FractalFraction commented on src/components/Dashboard/buildData.js
> +const buildLabelArray = (data) => {
Implemented changes.

2021-08-24 16:47 UTC, FractalFraction commented on src/components/Dashboard/buildData.js
> +const buildLabelArray = (data) => {
Made changes

2021-08-24 17:09 UTC, dearshrewdwit commented on src/components/Dashboard/buildData.js
> +const buildLabelArray = (data) => {
Effected changes did you?

2021-08-24 17:09 UTC, dearshrewdwit approved these changes

2021-08-25 08:06 UTC, richardtully approved these changes

2021-08-25 08:06 UTC, Reginmaru approved these changes

2021-08-25 08:06 UTC, merged