At 8
digital-futures-academy/atlas-frontend pull request #2
Opened 2021-08-18 14:26 UTC by rawdah123

Problem: Update front-end to request sorted data

Solution: We added some data to our cypress.json file and used this data to be presented on the browser. This data included name and date from the cohorts table. We also displayed the heading using html and we tested the display using cypress tests.

2021-08-18 14:38 UTC, dearshrewdwit requested changes
Good. Nice first steps.

See comments below

2021-08-18 14:38 UTC, dearshrewdwit commented on src/App.js
> +    //renders the component CohortList
Let's remove comments from code

2021-08-18 14:38 UTC, dearshrewdwit commented on src/components/Cohorts/Cohort.js
> +      <br></br>
Instead of using <br> elements, let's use CSS to style how this looks like.

Maybe use the style framework to help?

2021-08-18 14:38 UTC, dearshrewdwit commented on src/components/Cohorts/Cohort.js
> +//this returns the cohort from the props
Let's remove comments from code

2021-08-18 14:38 UTC, dearshrewdwit commented on src/components/Cohorts/CohortList.test.js
> +      "name": "test",
This should be an array of objects that represent cohorts. Currently you've just added more properties into the object representing cohort 1.

Look at the [fixture](https://github.com/digital-futures-academy/atlas-frontend/pull/2/files#diff-fb5e387f29e0f4276376eb8196efd00a11f86419244d436d845098b8c50319e1) for an idea of what I mean

2021-08-18 14:38 UTC, dearshrewdwit commented on src/components/Cohorts/CohortList.test.js
> +      "name": "test",
Can you add a component test to assert that both cohorts are shown on the page?

2021-08-18 14:38 UTC, dearshrewdwit commented on src/index.css
> +    background-color: pink;
:)

2021-08-18 14:38 UTC, dearshrewdwit commented on package.json
> +    "startbootstrap-freelancer": "^7.0.4",
Where is this being used?

2021-08-18 14:40 UTC, dearshrewdwit commented
@rawdah123 in addition, run `CI=true npm run build` locally to see whether it successfully builds - if it gives you errors, then it won't pass your tests when it runs on the CI server.

2021-08-19 08:03 UTC, dearshrewdwit commented
@rawdah123 what's the reasoning to create another react application within this one?

2021-08-19 08:55 UTC, breeshidy commented
> @rawdah123 what's the reasoning to create another react application within this one?
Hello @dearshrewdwit, would it be possible to delete this branch and start over?

2021-08-19 09:12 UTC, dearshrewdwit commented
> > @rawdah123 what's the reasoning to create another react application within this one?
> > Hello @dearshrewdwit, would it be possible to delete this branch and start over?

It's up to the owner of the work, looks like @rawdah123 ?

2021-08-19 09:30 UTC, closed without merging