At 60 implement editing student info on the frontend
digital-futures-academy/atlas-frontend pull request #25
Opened 2021-08-27 09:48 UTC by RyanVanDijck

2021-08-30 16:34 UTC, RyanVanDijck commented on src/components/Students/StudentInfo.test.js
> +  global.fetch = jest.fn(() => Promise.reject())
Changed here:
https://github.com/digital-futures-academy/atlas-frontend/pull/25/commits/ea38ea3acc8ccdd88c4bb87574696acd6915951b

2021-08-31 09:24 UTC, dearshrewdwit requested changes

2021-08-31 09:24 UTC, dearshrewdwit commented on src/components/Students/StudentInfo.js
> +                <this.check />
What's this doing?

2021-08-31 09:24 UTC, dearshrewdwit commented on src/components/Students/StudentInfo.js
> +    check = () => {
When does this fire?

2021-08-31 09:24 UTC, dearshrewdwit commented on src/components/Students/StudentInfo.js
> +    check = () => {
Instead - use the data from the response.

Your endpoint should be responsible for sending back a response with the information you need - for example on update:

Success:
```json
{
  "status": "success",
  "student": {
  },
  "errors": []
}
```
failure:
```json
{
  "status": "failure",
  "student": {
  },
  "errors": [
    "name can't be blank"
  ]
}
```

2021-08-31 09:24 UTC, dearshrewdwit commented on src/components/Students/StudentInfo.js
> +    check = () => {
Then you can check the status from the response and act accordingly

2021-09-01 08:58 UTC, RyanVanDijck commented on src/components/Students/StudentInfo.js
> +                <this.check />
Changed Here:
https://github.com/digital-futures-academy/atlas-frontend/pull/25/commits/c3a2e3b538bb8bfe9fc6609829ed1b0cebc2f7cf

2021-09-01 08:58 UTC, RyanVanDijck commented on src/components/Students/StudentInfo.js
> +    check = () => {
Changed Here:
https://github.com/digital-futures-academy/atlas-frontend/pull/25/commits/c3a2e3b538bb8bfe9fc6609829ed1b0cebc2f7cf

2021-09-02 09:20 UTC, dearshrewdwit commented
These test fail locally for me - can you investigate as well?

2021-09-02 09:21 UTC, RyanVanDijck commented
> ?

OK, I'll have a look.

2021-09-02 10:35 UTC, dearshrewdwit commented on cypress/integration/studentInfo.spec.js
> +        cy.intercept("http://localhost:5000/api/students/1", {status: 'failure'})
Check with @bferenczy0 , the API now sends back a consistent response, a failure has an error message you can use

2021-09-02 10:57 UTC, RyanVanDijck commented on cypress/integration/studentInfo.spec.js
> +        cy.intercept("http://localhost:5000/api/students/1", {status: 'failure'})
Changed here: 
https://github.com/digital-futures-academy/atlas-frontend/pull/25/commits/2c402e5792223a854d4fcb706f7124c6488ae55a

2021-09-02 14:34 UTC, dearshrewdwit requested changes

2021-09-02 14:34 UTC, dearshrewdwit commented on src/components/Students/StudentProfile/StudentInfo.js
> +        // .catch() when a student doesn't exist?
Remove these comments by adding an issue to your board with this work. And then we can merge this

2021-09-02 16:41 UTC, dearshrewdwit commented on cypress/integration/studentInfo.spec.js
> +  describe("Failed update for name too long", function() {
@bferenczy0 is this error message that gets returned from the API in this instance?

2021-09-02 16:41 UTC, dearshrewdwit commented on cypress/integration/studentInfo.spec.js
> +  describe("Failed update for name too long", function() {
>'Data over character limit'

2021-09-02 16:41 UTC, dearshrewdwit commented on cypress/integration/studentInfo.spec.js
> +      cy.get('#updateInput').type('J'.repeat(301))
ha - nice use of `repeat()`

2021-09-02 16:42 UTC, RyanVanDijck commented on cypress/integration/studentInfo.spec.js
> +  describe("Failed update for name too long", function() {
I don't think this check was implemented on the back end in AT-61

2021-09-02 16:44 UTC, dearshrewdwit commented on cypress/integration/studentInfo.spec.js
> +  describe("Failed update for name too long", function() {
https://github.com/digital-futures-academy/atlas-api/blob/main/routes/students.js#L50

2021-09-02 16:45 UTC, dearshrewdwit commented on cypress/integration/studentInfo.spec.js
> +  describe("Failed update for name too long", function() {
Looks like it catches any error from the update (a Sequelize error) and returns a response with the error message

2021-09-02 16:56 UTC, RyanVanDijck commented on cypress/integration/studentInfo.spec.js
> +  describe("Failed update for name too long", function() {
I'm not quite sure what that error would look like.

2021-09-02 17:22 UTC, dearshrewdwit commented on cypress/integration/studentInfo.spec.js
> +  describe("Failed update for name too long", function() {
```sh
curl -X PUT "http://localhost:5000/api/students/1" -d 'firstName=EdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdwardEdward'
{"status":"failure","student":{},"errors":"value too long for type character varying(255)"}
```

2021-09-02 19:16 UTC, RyanVanDijck commented on cypress/integration/studentInfo.spec.js
> +  describe("Failed update for name too long", function() {
Thank you. 
https://github.com/digital-futures-academy/atlas-frontend/commit/cca39a4ce3b85b83672a2e895f93f2078d777c50

2021-09-03 09:55 UTC, dearshrewdwit approved these changes

2021-09-03 09:57 UTC, bferenczy0 approved these changes

2021-09-03 09:58 UTC, merged