AT-94 moved the iframe to a specific div
digital-futures-academy/atlas-frontend pull request #26
Opened 2021-08-27 16:45 UTC by richardtully

Problem: the PDF was being generated behind the navbar and so you couldn't click all the buttons

Solution: changed our method to display the pdf in a specific div

Jira: https://dfacademy.atlassian.net/jira/software/projects/AT/boards/4?selectedIssue=AT-94

Next Steps: See if it works with the Navbar in place.

Co-authored by FractalFraction cln.gardiner@gmail.com

2021-08-31 09:12 UTC, dearshrewdwit requested changes
Nice - can you force squash into 1 commit?

2021-09-01 11:12 UTC, dearshrewdwit submitted a review, later dismissed
Nice job.

2021-09-01 13:01 UTC, FractalFraction submitted a review, later dismissed

2021-09-01 13:35 UTC, richardtully commented
Apologies Ed, you did already approve this but we had two branches just approved and they both involved changing the same file so we merged the other one and then this one needed a small conflict to be resolved.

2021-09-01 13:56 UTC, dearshrewdwit approved these changes

2021-09-01 14:03 UTC, b7rch4 approved these changes

2021-09-01 14:04 UTC, merged