At 100
digital-futures-academy/atlas-frontend pull request #39
Opened 2021-09-01 16:29 UTC by rawdah123

Problem: 
Remove the view details button.
When you hover over a cohort card, make the card outline bolder, and change the background colour - your choice.
When you click on the card, it navigates to the individual cohort page.

Solution:  Added Bootstrap card style to cohort list.

Jira Issue: https://dfacademy.atlassian.net/jira/software/projects/AT/boards/4?selectedIssue=AT-100

2021-09-01 17:53 UTC, dearshrewdwit requested changes
Good. See comment.

2021-09-01 17:53 UTC, dearshrewdwit commented on src/assets/css/styles.css
>      flex: 0 0 auto;
Remove commented code

2021-09-02 10:03 UTC, dearshrewdwit approved these changes

2021-09-02 10:21 UTC, AamirahV approved these changes

2021-09-02 10:21 UTC, merged

2021-09-02 10:23 UTC, dearshrewdwit commented
Please. Next time squash commits - this should be 1 commit.