AT-118: Added navigation button to student profile
digital-futures-academy/atlas-frontend pull request #43
Opened 2021-09-02 09:37 UTC by themegatree

Adding a link button to the student profile page ( https://dfacademy.atlassian.net/jira/software/projects/AT/boards/4?selectedIssue=AT-118 )

2021-09-02 09:45 UTC, dearshrewdwit commented on cypress/integration/students.spec.js
> +describe("Student - Link buttin works", function() {
typo: button

2021-09-02 09:50 UTC, dearshrewdwit requested changes
Instead - style the student data as a Card.

Remove the view details button.

When you hover over a student card, make the card outline bolder, and change the background colour - your choice.

When you click on the card, it navigates to the individual student page.

So the whole card should be an anchor link (<a href="url"></a>)

2021-09-03 10:18 UTC, themegatree commented
Changes made as requested

2021-09-03 10:37 UTC, dearshrewdwit commented on src/components/Students/StudentList/Student.js
> +      {/* <li className="btn btn-secondary"><a href={`${url}/${props.student.id}`} id={`button-${props.index}`}>View Profile</a></li> */}
Remove comment

2021-09-03 10:38 UTC, dearshrewdwit commented
Looks good otherwise

2021-09-03 10:41 UTC, themegatree commented on src/components/Students/StudentList/Student.js
> +      {/* <li className="btn btn-secondary"><a href={`${url}/${props.student.id}`} id={`button-${props.index}`}>View Profile</a></li> */}
Whoops...

2021-09-03 10:43 UTC, themegatree commented on src/components/Students/StudentList/Student.js
> +      {/* <li className="btn btn-secondary"><a href={`${url}/${props.student.id}`} id={`button-${props.index}`}>View Profile</a></li> */}
Change has been made

2021-09-03 10:52 UTC, dearshrewdwit approved these changes

2021-09-03 10:54 UTC, RyanVanDijck approved these changes

2021-09-03 10:54 UTC, merged