AT-8
digital-futures-academy/atlas-frontend pull request #7
Opened 2021-08-19 15:34 UTC by AamirahV

Problem: Update frontend to request sorted data
Solution: Still in progress
Jira Issue: https://dfacademy.atlassian.net/jira/software/projects/AT/boards/4?selectedIssue=AT-8

2021-08-19 15:41 UTC, dearshrewdwit commented on src/components/Cohorts/CohortList.test.js
> +  global.fetch = jest.fn(() => Promise.resolve({ json: () => Promise.resolve(data) }))
What's the reasoning behind mocking `fetch` here?

2021-08-19 15:41 UTC, dearshrewdwit commented on src/components/Cohorts/CohortList.test.js
> +  for (let i = 0; i < cohorts.length; i += 1) {
What is the purpose of this test?

2021-08-19 15:41 UTC, dearshrewdwit commented on src/components/Cohorts/CohortList.test.js
> +  await render(<CohortList cohorts={cohorts} />);
What is the purpose of all these component tests?

You're not asserting on the component in any way, simply asserting on the data you required from the module containing cohort list info.

2021-08-19 15:41 UTC, dearshrewdwit commented on src/components/Cohorts/Cohorts.test.js
> +import data, { cohorts } from './mocks/cohort-data.js'
What's the reasoning behind renaming this directory?

2021-08-20 09:58 UTC, breeshidy commented on src/components/Cohorts/Cohorts.test.js
> +import data, { cohorts } from './mocks/cohort-data.js'
When we import __mocks__, we get an error saying -- "Mocks should not be manually imported from a __mocks__ directory. Instead use `jest.mock` and import from the original module path.eslintjest/no-mocks-import". when we change the directory to "mocks" it worked fine

2021-08-20 10:00 UTC, breeshidy commented on src/components/Cohorts/CohortList.test.js
> +  global.fetch = jest.fn(() => Promise.resolve({ json: () => Promise.resolve(data) }))
This was simply so we don't have the populate a mock test array in the CohortList.test file

2021-08-20 10:02 UTC, breeshidy commented on src/components/Cohorts/CohortList.test.js
> +  for (let i = 0; i < cohorts.length; i += 1) {
To test the heading are appearing correctly but if it's not relevant, we can take it out

2021-08-20 10:03 UTC, dearshrewdwit commented on src/components/Cohorts/CohortList.test.js
> +  global.fetch = jest.fn(() => Promise.resolve({ json: () => Promise.resolve(data) }))
What's the connection between mocking fetch and importing data from the file?

2021-08-20 10:04 UTC, breeshidy commented on src/components/Cohorts/CohortList.test.js
> +  await render(<CohortList cohorts={cohorts} />);
The CohortList populates a ma function, so these tests were simply to check if the map function is populating correctly but if its unnecessary, we can take it out

2021-08-20 10:05 UTC, dearshrewdwit commented on src/components/Cohorts/CohortList.test.js
> +  for (let i = 0; i < cohorts.length; i += 1) {
This test doesn't assert on any component behaviour. It's importing data from a file and testing that it has the right state instead.

How can you assert on component behaviour instead?

2021-08-20 10:06 UTC, dearshrewdwit commented on src/components/Cohorts/CohortList.test.js
> +  await render(<CohortList cohorts={cohorts} />);
Assert on component behaviour - render the component and then check it displays the correct elements and the right content

2021-08-20 10:18 UTC, breeshidy commented on src/components/Cohorts/CohortList.test.js
> +  global.fetch = jest.fn(() => Promise.resolve({ json: () => Promise.resolve(data) }))
I am not sure what this question means exactly. Should we not use a fetch because I thought we needed to fetch to import data from the mock data file 😅

2021-08-20 10:24 UTC, breeshidy commented on src/components/Cohorts/CohortList.test.js
> +  await render(<CohortList cohorts={cohorts} />);
I am a little confused, I thought the tests were checking that it renders the right content and elements. the tests are using a mapped function to check if the mapping is displaying correctly or are we meant to use a different approach?

2021-08-20 10:30 UTC, dearshrewdwit commented on src/components/Cohorts/CohortList.test.js
> +  global.fetch = jest.fn(() => Promise.resolve({ json: () => Promise.resolve(data) }))
No, fetch is used to make HTTP requests.

https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

When a component makes an http request using fetch we mock the call and provide a response.

2021-08-20 10:37 UTC, dearshrewdwit commented on src/components/Cohorts/CohortList.test.js
> +  await render(<CohortList cohorts={cohorts} />);
You have to use react testing library to render the component and then query the page to find elements and assert that they have the right content. Have a look at the example.

Currently these tests will pass if you don't render the component!!

2021-08-20 10:40 UTC, dearshrewdwit commented on src/components/Cohorts/CohortList.test.js
> +  await render(<CohortList cohorts={cohorts} />);
Here's an example: 

https://github.com/digital-futures-academy/atlas-frontend/blob/main/src/components/Cohorts/CohortList.test.js

Can you see how the component renders and then is queried for an element, and the element asserted on?

2021-08-24 11:09 UTC, dearshrewdwit requested changes

2021-08-24 11:09 UTC, dearshrewdwit commented on src/components/Cohorts/Cohorts.test.js
> +test("Renders Cohort's List", async () => {
Guys, let's jump on a call - this is still a useless test - you're asserting on your mock data, not on the component behaviour.

2021-08-30 21:29 UTC, breeshidy commented on src/components/Cohorts/CohortList.test.js
> +jest.mock('react-router-dom', () => ({
This is because of the useRouter method-- in jest test, it keeps coming up as location undefined until I mocked it

2021-08-30 21:31 UTC, breeshidy commented on src/components/NavBar.js
> +import BodyReports from './Reports/BootstrapStyles/Body'
its now removed

2021-08-31 09:26 UTC, dearshrewdwit approved these changes

2021-08-31 09:26 UTC, dearshrewdwit commented
Let's get it in 👍

2021-08-31 09:36 UTC, breeshidy approved these changes

2021-08-31 09:36 UTC, merged