AT-13-File Uploader
digital-futures-academy/atlas-frontend pull request #8
Opened 2021-08-20 17:32 UTC by grantwhiteman

Created front end for file uploader, takes input of a file and shows success or errors.
Tested with Cypress in API spec

2021-08-24 11:11 UTC, dearshrewdwit requested changes

2021-08-24 11:11 UTC, dearshrewdwit commented on package.json
> +<<<<<<< HEAD
👀

2021-08-24 15:44 UTC, benclayton98 commented on package.json
> +<<<<<<< HEAD
we've made this change but the jenkins tests on github are still failing, are they supposed to be?

2021-08-24 15:50 UTC, dearshrewdwit commented on package.json
> +<<<<<<< HEAD
You left a bunch of conflict remnants in this file!

2021-08-24 15:52 UTC, benclayton98 commented on package.json
> +<<<<<<< HEAD
Oh my bad! Think that was from a rebase that didn't work as intended

2021-08-24 15:53 UTC, dearshrewdwit requested changes
CI is currently failing

```sh
+ npm run build
> atlas-frontend@0.1.0 build
> react-scripts build
Creating an optimized production build...
Treating warnings as errors because process.env.CI = true.
Most CI servers set it automatically.

Failed to compile.

src/components/Upload/Response.js
  Line 4:5:  Useless constructor  no-useless-constructor
script returned exit code 1
```

To fix - change the stateful component into a stateless component (class -> functional)

2021-08-24 16:29 UTC, b7rch4 submitted a review, later dismissed

2021-08-24 16:32 UTC, dearshrewdwit commented
Very tempted to ask you to force squash your commits - this should be a habit!

28 commits is a large number for any 1 feature.

2021-08-25 09:54 UTC, dearshrewdwit approved these changes

2021-08-25 09:57 UTC, Neokrieger approved these changes
Very good

2021-08-25 09:57 UTC, merged