AT-37 Creating student page on frontend
digital-futures-academy/atlas-frontend pull request #9
Opened 2021-08-23 09:51 UTC by RyanVanDijck

2021-08-23 10:15 UTC, dearshrewdwit requested changes
Make sure you run `CI=true npm run build` locally and fix any errors - currently the PR is not passing CI tests

I'll review when it passes 👍

2021-08-23 10:28 UTC, dearshrewdwit requested changes

2021-08-23 10:28 UTC, dearshrewdwit commented on src/App.js
> +              <Route exact path='/student/:id'>
Resources are almost always plural in URLs:  should be `/students/:id`

2021-08-23 10:28 UTC, dearshrewdwit commented on src/components/Students/StudentInfo.js
> +        await fetch(`${process.env.REACT_APP_API_URL}/api/students:${this.state.id}`)
Is this URL formed correctly - should it not be `/api/students/{this.state.id}` ?

Check your endpoint :)

2021-08-23 10:28 UTC, dearshrewdwit commented on src/components/Students/StudentInfo.js
> +            id: props.id,
Do you need to set state for `id`?  Could you leave it as a property, and access it via `this.props.id`?

2021-08-23 10:44 UTC, RyanVanDijck commented on src/components/Students/StudentInfo.js
> +            id: props.id,
Ah, this was left over from the old solution. 

Fixed here:
https://github.com/digital-futures-academy/atlas-frontend/pull/9/commits/a9035ceaf3fa03ab9685a5ebeeb6643f125c7600

2021-08-23 10:46 UTC, RyanVanDijck commented on src/components/Students/StudentInfo.js
> +        await fetch(`${process.env.REACT_APP_API_URL}/api/students:${this.state.id}`)
Fixed here:

https://github.com/digital-futures-academy/atlas-frontend/pull/9/commits/a9035ceaf3fa03ab9685a5ebeeb6643f125c7600

2021-08-23 13:11 UTC, RyanVanDijck commented on src/App.js
> +              <Route exact path='/student/:id'>
Fixed here:
https://github.com/digital-futures-academy/atlas-frontend/pull/9/commits/2777305e92270cde87d39a14d5e941b6b0c89e9a

2021-08-23 13:25 UTC, dearshrewdwit approved these changes

2021-08-24 09:06 UTC, bferenczy0 approved these changes

2021-08-24 09:06 UTC, merged